background_opacity    0.8
cursor_trail          9
window_padding_width  25
cursor_blink_interval 0
font_family           Maple Mono NF
font_size             14.0

shell_integration enabled
enabled_layouts fat:bias=50;full_size=1;mirrored=false

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

map ctrl+shift+enter launch --location=split --cwd=current

map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

scrollback_lines 10000
url_color #8be9fd
underline_hyperlinks always
copy_on_select clipboard
strip_trailing_spaces smart

tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{title}"

include themes/noctalia.conf
