unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
set -sa terminal-overrides ",xterm*:Tc"
set -sg escape-time 0

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n S-Left previous-window
bind -n S-Right next-window
bind -n M-H previous-window
bind -n M-L next-window

bind -n C-Enter split-window -v -c "#{pane_current_path}"
bind -n C-M-Enter split-window -h -c "#{pane_current_path}"bind -n Escape "[13;5u" split-window -v -c "#{pane_current_path}"
bind -n Escape "[13;6u" split-window -h -c "#{pane_current_path}"

bind -n Escape "[9;5u" next-window
bind -n Escape "[9;6u" previous-window

bind -n C-Tab next-window
bind -n C-S-Tab previous-window

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set-window-option -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind-key C-w
unbind-key -n C-w
