unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
set -sg escape-time 0

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n S-Left previous-window
bind -n S-Right next-window

bind-key -n C-S-Enter split-window -v -c "#{pane_current_path}"
bind-key -n C-M-Enter split-window -h -c "#{pane_current_path}"

bind -n C-Tab next-window
bind -n C-S-BTab previous-window
bind-key -n M-w kill-pane
bind -n C-t new-window -c "#{pane_current_path}"

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

set -g status-position bottom
set -g status-interval 5

set -g window-status-format "#[fg=#565f89,bg=#1a1b26] #{pane_title} "
set -g window-status-current-format "#[fg=#1a1b26,bg=#bb9af7,bold] #{pane_title} "

set -g status-left ""
set -g status-right ""

set -g status-justify centre

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind-key C-w
unbind-key -n C-w
