[colors.primary]
background = '#2e3440'
foreground = '#d8dee9'

[colors.cursor]
text = '#282828'
cursor = '#eceff4'

[colors.vi_mode_cursor]
text = '#2e3440'
cursor = '#8fbcbb'

[colors.search.matches]
foreground = '#3b4252'
background = '#5e81ac'

[colors.search.focused_match]
foreground = '#3b4252'
background = '#8fbcbb'

[colors.footer_bar]
foreground = '#3b4252'
background = '#e3e5e8'

[colors.hints.start]
foreground = '#3b4252'
background = '#88c0d0'

[colors.hints.end]
foreground = '#3b4252'
background = '#88c0d0'

[colors.selection]
text = '#4c566a'
background = '#eceff4'


[colors.normal]
black   = '#3b4252'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#ebcb8b'
blue    = '#81a1c1'
magenta = '#b48ead'
cyan    = '#88c0d0'
white   = '#e5e9f0'


[colors.bright]
black   = '#596377'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#ebcb8b'
blue    = '#81a1c1'
magenta = '#b48ead'
cyan    = '#8fbcbb'
white   = '#eceff4'


[colors.dim]
black   = '#3b4252'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#ebcb8b'
blue    = '#81a1c1'
magenta = '#b48ead'
cyan    = '#88c0d0'
white   = '#e5e9f0'
